name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout no código
    - uses: action/checkout@v2
    - name: Subir o artefato
    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.ARTIFACT_NAME}}
        path: .
