name: first

on: push

jobs:
    
    job1: 
      name: Primeiro Job
      runs-on: ubuntu-latest
      steps:
      - name: Primeiro Passo
        uses: actions/checkout@v2
      - name: Segundo Passo
        run: env | sort 
    
    job2: 
      name: Segundo Job
      runs-on: windows-latest
      steps:
      - name: Primeiro Passo
        uses: actions/checkout@v2
      - name: Segundo Passo
        run: "Get-ChildItem Env: | Sort-Object Name"
